version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tg_journal"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    container_name: postgres-db
    volumes:
        - ../2. Init Database:/docker-entrypoint-initdb.d
        - .:/var/lib/postgresql/data

    ports:
        - "5432:5432"
